# Generated by Django 5.2.7 on 2025-11-11 19:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookExportView',
            fields=[
                ('isbn', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('book_title', models.CharField(max_length=512)),
                ('authors', models.TextField()),
                ('publisher', models.CharField(blank=True, max_length=255, null=True)),
                ('year_of_publication', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('avg_rating', models.FloatField(blank=True, null=True)),
                ('total_ratings', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'book_export_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookReaderModel',
            fields=[
                ('user_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='PublisherModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookStoreModel',
            fields=[
                ('isbn', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('book_title', models.CharField(max_length=512)),
                ('year_of_publication', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('img_s', models.URLField(blank=True, max_length=512, null=True)),
                ('img_m', models.URLField(blank=True, max_length=512, null=True)),
                ('img_l', models.URLField(blank=True, max_length=512, null=True)),
                ('authors', models.ManyToManyField(related_name='books', to='bookstore.authormodel')),
                ('publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publisher_books', to='bookstore.publishermodel')),
            ],
        ),
        migrations.CreateModel(
            name='BookRatingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_ratings', to='bookstore.bookreadermodel')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='bookstore.bookstoremodel')),
            ],
            options={
                'unique_together': {('user', 'book')},
            },
        ),
    ]
