# Generated by Django 5.2.7 on 2025-11-10 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                CREATE MATERIALIZED VIEW book_export_view AS
                SELECT 
                    b.isbn,
                    b.book_title,
                    STRING_AGG(DISTINCT a.name, ', ') AS authors,
                    p.name AS publisher,
                    b.year_of_publication,
                    ROUND(AVG(r.rating)::numeric, 2) AS avg_rating,
                    COUNT(r.rating) AS total_ratings
                FROM
                    bookstore_bookstoremodel b
                LEFT JOIN
                    bookstore_bookstoremodel_authors ba ON b.isbn = ba.bookstoremodel_id
                LEFT JOIN
                    bookstore_authormodel a ON a.id = ba.authormodel_id
                LEFT JOIN
                    bookstore_publishermodel p ON b.publisher_id = p.id
                LEFT JOIN
                    bookstore_bookratingmodel r ON b.isbn = r.book_id
                GROUP BY
                    b.isbn, b.book_title, p.name, b.year_of_publication;
            """,
            reverse_sql="DROP MATERIALIZED VIEW IF EXISTS book_export_view;"
        ),
    ]
